ALTER TABLE video ALTER COLUMN name DROP NOT NULL;
ALTER TABLE video ALTER COLUMN url DROP NOT NULL;
ALTER TABLE video ALTER COLUMN customer_id DROP NOT NULL;
ALTER TABLE video ALTER COLUMN created_at DROP NOT NULL;
